# Generated by Django 4.0.1 on 2022-12-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keysecrets', '0001_initial'),
        ('profiles', '0001_initial'),
        ('userstrategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=16)),
                ('balance', models.FloatField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilewalletbalance', to='profiles.profile')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretwalletbalance', to='keysecrets.secret')),
            ],
            options={
                'db_table': 'walletbalance',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('balance', models.FloatField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilebalance', to='profiles.profile')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategybalance', to='userstrategies.userstrategy')),
            ],
            options={
                'db_table': 'balance',
            },
        ),
    ]
