# Generated by Django 4.0.1 on 2022-11-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userstrategies', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activatePrice', models.FloatField(blank=True, null=True)),
                ('avgPrice', models.FloatField()),
                ('clientOrderId', models.CharField(max_length=32)),
                ('closePosition', models.BooleanField()),
                ('cumQty', models.FloatField()),
                ('cumQuote', models.FloatField()),
                ('executedQty', models.FloatField()),
                ('orderId', models.BigIntegerField(unique=True)),
                ('origQty', models.FloatField()),
                ('origType', models.CharField(max_length=32)),
                ('positionSide', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('priceProtect', models.BooleanField()),
                ('priceRate', models.FloatField(blank=True, null=True)),
                ('reduceOnly', models.BooleanField()),
                ('side', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('stopPrice', models.FloatField()),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('timeInForce', models.CharField(max_length=16)),
                ('orderType', models.CharField(db_index=True, max_length=32)),
                ('updateTime', models.BigIntegerField(db_index=True)),
                ('workingType', models.CharField(max_length=16)),
                ('tardeMatched', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileorder', to='profiles.profile')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyorder', to='userstrategies.userstrategy')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-updateTime'],
            },
        ),
        migrations.CreateModel(
            name='CanceledOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('detail', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOrderCancel', to='profiles.profile')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyOrderCancel', to='userstrategies.userstrategy')),
            ],
            options={
                'db_table': 'canceledOrders',
                'ordering': ['-createTime'],
            },
        ),
    ]
