# Generated by Django 4.0.1 on 2022-12-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletName', models.CharField(blank=True, max_length=256, null=True)),
                ('apiKey', models.CharField(max_length=256)),
                ('secretKey', models.CharField(max_length=256)),
                ('uniquesign', models.CharField(max_length=16)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilesecret', to='profiles.profile')),
            ],
            options={
                'db_table': 'secrets',
                'unique_together': {('uniquesign',)},
            },
        ),
    ]
