# Generated by Django 4.0.1 on 2022-11-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(default='default.png', upload_to='profile_pics', validators=[stdimage.validators.MinSizeValidator(200, 200), stdimage.validators.MaxSizeValidator(500, 500)])),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('addressVerified', models.BooleanField(default=False)),
                ('cellPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cellPhoneNumberVerified', models.BooleanField(default=False)),
                ('landingPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('landingPhoneNumberVerified', models.BooleanField(default=False)),
                ('signedContract', models.BooleanField(db_index=True, default=False)),
                ('payedMemmber', models.BooleanField(db_index=True, default=False)),
                ('paymentTime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expirationTime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('isEnable', models.BooleanField(db_index=True, default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('totalSL', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
