# Generated by Django 4.0.1 on 2022-09-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_person_createdtime_person_is_allow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_allow',
            new_name='is_allowed',
        ),
    ]
