# Generated by Django 4.0.1 on 2022-09-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_rename_is_allow_person_is_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_allowed',
            new_name='isAllowed',
        ),
    ]
