# Generated by Django 4.0.1 on 2022-11-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keysecrets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=32)),
                ('symbol', models.CharField(choices=[('RAYUSDT', 'RAYUSDT'), ('API3USDT', 'API3USDT'), ('SUSHIUSDT', 'SUSHIUSDT'), ('CVCUSDT', 'CVCUSDT'), ('BTSUSDT', 'BTSUSDT'), ('HOTUSDT', 'HOTUSDT'), ('ZRXUSDT', 'ZRXUSDT'), ('QTUMUSDT', 'QTUMUSDT'), ('IOTAUSDT', 'IOTAUSDT'), ('BTCBUSD', 'BTCBUSD'), ('WAVESUSDT', 'WAVESUSDT'), ('ADAUSDT', 'ADAUSDT'), ('LITUSDT', 'LITUSDT'), ('XTZUSDT', 'XTZUSDT'), ('BNBUSDT', 'BNBUSDT'), ('AKROUSDT', 'AKROUSDT'), ('HNTUSDT', 'HNTUSDT'), ('ETCUSDT', 'ETCUSDT'), ('XMRUSDT', 'XMRUSDT'), ('YFIUSDT', 'YFIUSDT'), ('FTTBUSD', 'FTTBUSD'), ('ETHUSDT', 'ETHUSDT'), ('ALICEUSDT', 'ALICEUSDT'), ('ALPHAUSDT', 'ALPHAUSDT'), ('SFPUSDT', 'SFPUSDT'), ('REEFUSDT', 'REEFUSDT'), ('BATUSDT', 'BATUSDT'), ('DOGEUSDT', 'DOGEUSDT'), ('TRXUSDT', 'TRXUSDT'), ('RLCUSDT', 'RLCUSDT'), ('BTCSTUSDT', 'BTCSTUSDT'), ('STORJUSDT', 'STORJUSDT'), ('SNXUSDT', 'SNXUSDT'), ('1000XECUSDT', '1000XECUSDT'), ('AUDIOUSDT', 'AUDIOUSDT'), ('XLMUSDT', 'XLMUSDT'), ('IOTXUSDT', 'IOTXUSDT'), ('NEOUSDT', 'NEOUSDT'), ('UNFIUSDT', 'UNFIUSDT'), ('SANDUSDT', 'SANDUSDT'), ('DASHUSDT', 'DASHUSDT'), ('KAVAUSDT', 'KAVAUSDT'), ('RUNEUSDT', 'RUNEUSDT'), ('CTKUSDT', 'CTKUSDT'), ('LINKUSDT', 'LINKUSDT'), ('CELRUSDT', 'CELRUSDT'), ('RSRUSDT', 'RSRUSDT'), ('ADABUSD', 'ADABUSD'), ('DGBUSDT', 'DGBUSDT'), ('SKLUSDT', 'SKLUSDT'), ('RENUSDT', 'RENUSDT'), ('LPTUSDT', 'LPTUSDT'), ('TOMOUSDT', 'TOMOUSDT'), ('MTLUSDT', 'MTLUSDT'), ('LTCUSDT', 'LTCUSDT'), ('DODOUSDT', 'DODOUSDT'), ('EGLDUSDT', 'EGLDUSDT'), ('KSMUSDT', 'KSMUSDT'), ('BNBBUSD', 'BNBBUSD'), ('ONTUSDT', 'ONTUSDT'), ('VETUSDT', 'VETUSDT'), ('IMXUSDT', 'IMXUSDT'), ('TRBUSDT', 'TRBUSDT'), ('MANAUSDT', 'MANAUSDT'), ('FLOWUSDT', 'FLOWUSDT'), ('COTIUSDT', 'COTIUSDT'), ('CHRUSDT', 'CHRUSDT'), ('BAKEUSDT', 'BAKEUSDT'), ('GRTUSDT', 'GRTUSDT'), ('ETHUSDT_220325', 'ETHUSDT_220325'), ('FLMUSDT', 'FLMUSDT'), ('MASKUSDT', 'MASKUSDT'), ('EOSUSDT', 'EOSUSDT'), ('OGNUSDT', 'OGNUSDT'), ('SCUSDT', 'SCUSDT'), ('BALUSDT', 'BALUSDT'), ('STMXUSDT', 'STMXUSDT'), ('LUNAUSDT', 'LUNAUSDT'), ('DENTUSDT', 'DENTUSDT'), ('1000BTTCUSDT', '1000BTTCUSDT'), ('KNCUSDT', 'KNCUSDT'), ('SRMUSDT', 'SRMUSDT'), ('ENJUSDT', 'ENJUSDT'), ('C98USDT', 'C98USDT'), ('ZENUSDT', 'ZENUSDT'), ('ATOMUSDT', 'ATOMUSDT'), ('NEARUSDT', 'NEARUSDT'), ('SOLBUSD', 'SOLBUSD'), ('ENSUSDT', 'ENSUSDT'), ('BCHUSDT', 'BCHUSDT'), ('ATAUSDT', 'ATAUSDT'), ('IOSTUSDT', 'IOSTUSDT'), ('HBARUSDT', 'HBARUSDT'), ('ZECUSDT', 'ZECUSDT'), ('1000SHIBUSDT', '1000SHIBUSDT'), ('TLMUSDT', 'TLMUSDT'), ('ANTUSDT', 'ANTUSDT'), ('ETHBUSD', 'ETHBUSD'), ('GALAUSDT', 'GALAUSDT'), ('AAVEUSDT', 'AAVEUSDT'), ('GTCUSDT', 'GTCUSDT'), ('ALGOUSDT', 'ALGOUSDT'), ('ICPUSDT', 'ICPUSDT'), ('LRCUSDT', 'LRCUSDT'), ('AVAXUSDT', 'AVAXUSDT'), ('BTCUSDT_220325', 'BTCUSDT_220325'), ('ARPAUSDT', 'ARPAUSDT'), ('CELOUSDT', 'CELOUSDT'), ('ROSEUSDT', 'ROSEUSDT'), ('MATICUSDT', 'MATICUSDT'), ('1INCHUSDT', '1INCHUSDT'), ('MKRUSDT', 'MKRUSDT'), ('PEOPLEUSDT', 'PEOPLEUSDT'), ('THETAUSDT', 'THETAUSDT'), ('UNIUSDT', 'UNIUSDT'), ('LINAUSDT', 'LINAUSDT'), ('ARUSDT', 'ARUSDT'), ('RVNUSDT', 'RVNUSDT'), ('FILUSDT', 'FILUSDT'), ('NKNUSDT', 'NKNUSDT'), ('KLAYUSDT', 'KLAYUSDT'), ('DEFIUSDT', 'DEFIUSDT'), ('COMPUSDT', 'COMPUSDT'), ('BTCDOMUSDT', 'BTCDOMUSDT'), ('SOLUSDT', 'SOLUSDT'), ('BTCUSDT', 'BTCUSDT'), ('OMGUSDT', 'OMGUSDT'), ('ICXUSDT', 'ICXUSDT'), ('BLZUSDT', 'BLZUSDT'), ('FTMUSDT', 'FTMUSDT'), ('YFIIUSDT', 'YFIIUSDT'), ('BANDUSDT', 'BANDUSDT'), ('XRPBUSD', 'XRPBUSD'), ('DOGEBUSD', 'DOGEBUSD'), ('XRPUSDT', 'XRPUSDT'), ('SXPUSDT', 'SXPUSDT'), ('CRVUSDT', 'CRVUSDT'), ('BELUSDT', 'BELUSDT'), ('DOTUSDT', 'DOTUSDT'), ('XEMUSDT', 'XEMUSDT'), ('ONEUSDT', 'ONEUSDT'), ('ZILUSDT', 'ZILUSDT'), ('AXSUSDT', 'AXSUSDT'), ('DYDXUSDT', 'DYDXUSDT'), ('OCEANUSDT', 'OCEANUSDT'), ('CHZUSDT', 'CHZUSDT'), ('ANKRUSDT', 'ANKRUSDT'), ('DUSKUSDT', 'DUSKUSDT'), ('CTSIUSDT', 'CTSIUSDT')], default='BTCUSDT', max_length=14)),
                ('margin', models.FloatField()),
                ('totallSL', models.FloatField()),
                ('risk', models.FloatField()),
                ('size', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=False)),
                ('baseCurrency', models.CharField(choices=[('USDT', 'USDT'), ('BUSD', 'BUSD'), ('BNB', 'BNB')], default='USDT', max_length=4)),
                ('leverage', models.IntegerField(default=1)),
                ('marginType', models.CharField(choices=[('ISOLATED', 'ISOLATED'), ('CROSSED', 'CROSSED')], default='ISOLATED', max_length=10)),
                ('positionMode', models.CharField(choices=[('One-way', 'One-way'), ('Hedge', 'Hedge')], default='One-way', max_length=7)),
                ('timeInForce', models.CharField(choices=[('GTC', 'GTC'), ('IOC', 'IOC'), ('FOK', 'FOK')], default='GTC', max_length=3)),
                ('workingType', models.CharField(choices=[('MARK_PRICE', 'MARK_PRICE'), ('CONTRACT_PRICE', 'CONTRACT_PRICE')], default='CONTRACT_PRICE', max_length=14)),
                ('priceProtect', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('deactivateTime', models.DateTimeField(blank=True, null=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretuserstrategy', to='keysecrets.secret')),
            ],
            options={
                'db_table': 'user_strategy',
            },
        ),
    ]
