# Generated by Django 4.0.1 on 2022-12-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keysecrets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=32)),
                ('margin', models.FloatField()),
                ('totallSL', models.FloatField()),
                ('risk', models.FloatField()),
                ('size', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=False)),
                ('baseCurrency', models.CharField(choices=[('USDT', 'USDT'), ('BUSD', 'BUSD'), ('BNB', 'BNB')], default='USDT', max_length=4)),
                ('leverage', models.IntegerField(default=1)),
                ('marginType', models.CharField(choices=[('ISOLATED', 'ISOLATED'), ('CROSSED', 'CROSSED')], default='ISOLATED', max_length=10)),
                ('positionMode', models.CharField(choices=[('One-way', 'One-way'), ('Hedge', 'Hedge')], default='One-way', max_length=7)),
                ('timeInForce', models.CharField(choices=[('GTC', 'GTC'), ('IOC', 'IOC'), ('FOK', 'FOK')], default='GTC', max_length=3)),
                ('workingType', models.CharField(choices=[('MARK_PRICE', 'MARK_PRICE'), ('CONTRACT_PRICE', 'CONTRACT_PRICE')], default='CONTRACT_PRICE', max_length=14)),
                ('priceProtect', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('deactivateTime', models.DateTimeField(blank=True, null=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretuserstrategy', to='keysecrets.secret')),
                ('symbols', models.ManyToManyField(related_name='userstrategys', to='userstrategies.Symbol')),
            ],
            options={
                'db_table': 'user_strategy',
            },
        ),
    ]
