# Generated by Django 4.0.1 on 2022-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstrategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstrategy',
            name='symbol',
        ),
        migrations.AddField(
            model_name='userstrategy',
            name='symbols',
            field=models.ManyToManyField(related_name='userstrategys', to='userstrategies.Symbol'),
        ),
    ]
