# Generated by Django 4.0.1 on 2022-12-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keysecrets', '0001_initial'),
        ('profiles', '0001_initial'),
        ('userstrategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnplanTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('tradeId', models.BigIntegerField(unique=True)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(db_index=True, max_length=16)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField(db_index=True)),
                ('marginAsset', models.CharField(max_length=16)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField(db_index=True)),
                ('commissionAsset', models.CharField(max_length=16)),
                ('time', models.BigIntegerField(db_index=True)),
                ('positionSide', models.CharField(db_index=True, max_length=16)),
                ('buyer', models.BooleanField()),
                ('maker', models.BooleanField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretunplantrade', to='keysecrets.secret')),
            ],
            options={
                'db_table': 'unplantrades',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('tradeId', models.BigIntegerField(unique=True)),
                ('orderId', models.BigIntegerField()),
                ('side', models.CharField(db_index=True, max_length=16)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('realizedPnl', models.FloatField(db_index=True)),
                ('marginAsset', models.CharField(max_length=16)),
                ('quoteQty', models.FloatField()),
                ('commission', models.FloatField(db_index=True)),
                ('commissionAsset', models.CharField(max_length=16)),
                ('time', models.BigIntegerField(db_index=True)),
                ('positionSide', models.CharField(db_index=True, max_length=16)),
                ('buyer', models.BooleanField()),
                ('maker', models.BooleanField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiletrade', to='profiles.profile')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategytrade', to='userstrategies.userstrategy')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-time'],
            },
        ),
    ]
